# Generated by Django 4.1.7 on 2023-04-01 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_solvedcomplaint_unsolvedcomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='solvedComplaint',
        ),
        migrations.DeleteModel(
            name='unsolvedComplaint',
        ),
        migrations.RemoveField(
            model_name='allcomplaint',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='allcomplaint',
            name='comtype',
        ),
        migrations.RemoveField(
            model_name='allcomplaint',
            name='created',
        ),
        migrations.RemoveField(
            model_name='allcomplaint',
            name='decss',
        ),
        migrations.RemoveField(
            model_name='allcomplaint',
            name='name',
        ),
        migrations.AddField(
            model_name='allcomplaint',
            name='Description',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='allcomplaint',
            name='Subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allcomplaint',
            name='Time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allcomplaint',
            name='Type_of_complaint',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='allcomplaint',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
